variables:
  vmImageName: 'ubuntu-latest'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - $(workingDirectory)
    - pipeline/gitguardian.yml

stages:
  - stage: Gitguardian
    displayName: gitguardian_code
    jobs:
    - job: GitGuardianShield
      pool: 
        vmImage: $(vmImageName)
      container:
        image: gitguardian/ggshield:latest
        options: -u 0
      steps:
        - task: AzureKeyVault@2
          inputs:
            azureSubscription: 'test-sp'
            KeyVaultName: 'vkkeyvault2022'
            SecretsFilter: 'GITGUARDIANAPIKEY'
            RunAsPreJob: true
        - script: ggshield secret scan ci
          env:
            GITGUARDIAN_API_KEY: $(GITGUARDIANAPIKEY)
